<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <!-- El DatabaseInitializer busca este archivo en AppContext.BaseDirectory/Sql/ -->
    <None Include="Sql/schema.sql" CopyToOutputDirectory="PreserveNewest" Link="Sql/modulo05_schema.sql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../01_Core/Intranet.Core/Intranet.Core.csproj" />
  </ItemGroup>
</Project>
